import type { Metadata } from "next";
import { Inter } from "next/font/google";

import PreviewBar from "/components/common/PreviewBar"

import "/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" className={inter.className}>
        <body >
          <div id="site-wrapper">
          <div id="site">
              <PreviewBar />
              <div className="flex flex-col min-h-screen">  
                <main className={`flex-grow`}>{children}</main>
              </div>
            </div>
          </div>
        </body>
      </html>
  );
}
